
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package LexicoSintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int program = 17;
  public static final int function = 22;
  public static final int op_resta = 3;
  public static final int numeric_real_const = 43;
  public static final int word_if = 32;
  public static final int op_suma = 2;
  public static final int word_const = 16;
  public static final int opr_mayor_igual = 29;
  public static final int coma = 9;
  public static final int word_repeat = 36;
  public static final int opr_iguales = 25;
  public static final int identifier = 42;
  public static final int punto_y_coma = 10;
  public static final int begin = 18;
  public static final int real = 15;
  public static final int opr_menor_igual = 28;
  public static final int opl_and = 31;
  public static final int end = 19;
  public static final int cierra_parent = 8;
  public static final int word_to = 40;
  public static final int var = 20;
  public static final int word_until = 37;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int opl_or = 30;
  public static final int op_div = 6;
  public static final int procedure = 21;
  public static final int punto = 11;
  public static final int word_do = 39;
  public static final int dospuntos = 13;
  public static final int integer = 14;
  public static final int word_else = 34;
  public static final int abre_parent = 7;
  public static final int op_mod = 5;
  public static final int word_then = 33;
  public static final int unit = 24;
  public static final int op_mult = 4;
  public static final int not = 23;
  public static final int opr_menor = 26;
  public static final int word_for = 38;
  public static final int word_while = 35;
  public static final int numeric_integer_const = 44;
  public static final int string_const = 45;
  public static final int opr_mayor = 27;
  public static final int asignacion = 12;
  public static final int word_downto = 41;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "op_suma",
  "op_resta",
  "op_mult",
  "op_mod",
  "op_div",
  "abre_parent",
  "cierra_parent",
  "coma",
  "punto_y_coma",
  "punto",
  "asignacion",
  "dospuntos",
  "integer",
  "real",
  "word_const",
  "program",
  "begin",
  "end",
  "var",
  "procedure",
  "function",
  "not",
  "unit",
  "opr_iguales",
  "opr_menor",
  "opr_mayor",
  "opr_menor_igual",
  "opr_mayor_igual",
  "opl_or",
  "opl_and",
  "word_if",
  "word_then",
  "word_else",
  "word_while",
  "word_repeat",
  "word_until",
  "word_for",
  "word_do",
  "word_to",
  "word_downto",
  "identifier",
  "numeric_real_const",
  "numeric_integer_const",
  "string_const"
  };
}

